# -*- coding: utf-8 -*-
"""ch1_class-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1meSnIJMM8uz5qJ05jXPKv-tiyT90fiCo
"""

a = '1'
b = "2"
c = a + b
print(c)
print(type(c))

a = '1'
b = "2"
c = a + b
print(c)
print(type(c))

a = int(a)
b = int(b)
c = a+b
print(c)
print(type(c))

print(4*(2+3))
print(2**10)
print(64//7)
print(64%7)

a = 'apple'
print('an', a , 'a day keeps the doctor away')

a = 'apple'
print('an'+ a + 'a day keeps the doctor away')

b = 10
print( b , 'apples a day keeps the doctor away')

b = 10
print( b + 'apples a day keeps the doctor away')

# Python格式化的兩種方式
person = 'Marry'
year = 20
height = 168.2
print('{} is {} years old, she is {}cm tall '.format(person, year, height))  #新式
print('%s is %d years old, she is %fcm tall' % (person, year, height))       #舊式