# -*- coding: utf-8 -*-
"""ch1_lab-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16KY3UGWiPKqX_fnKIcd1ZIv7CRwxmHyZ
"""

a = int(input())
b = int(input())
c = a+b
print(c)