# -*- coding: utf-8 -*-
"""語法-CH1 基礎.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gP8FOwukyxQH41OyosttSTvRmULn9v7S
"""

print('Hello World!')

input()

input() #輸入的語法是input()

x = 'Hello World!'
print(x)

a = 'Hello World!'
b = 1
c = 3.14
d = True
print(type(a))
print(type(b))
print(type(c))
print(type(d))

x = 1
y = 2
z = x+y
print(z)

print(type(z))

Aa = 1
b2 = 3.1415926
_c = 'Hello World!'

1a = 1
@b = 3.1415926

a = 1
b = a + 1


print(b)

a = 'ABC'
b = a
a = 'XYZ'
print(a)
print(b)

a = input('請輸入數字')
print(a)
print(type(a))

a = int(a)
print(a)
print(type(a))

b = input('請輸入數字')
print(b)
print(type(b))

b = float(b)
print(b)
print(type(b))

a = int(input())
b = int(input())
c = a+b
print(c)

print(4*(2+3))
print(2**10)
print(64//7)
print(64%7)

eng = int(input())
math = int(input())
if ( eng and math ) >= 60 :
  print('吃海底撈')

elif ( eng or math ) >= 60 :
  print('吃肯德基')

else:
  print('去罰站')

print('正午的濕度預測約有80%，','因此很可能有午後雷陣雨')

print('正午的濕度預測約有80%，'+'因此很可能有午後雷陣雨')

a = 'apple'
print('an', a , 'a day keeps the doctor away')

a = 'apple'
print('an'+ a + 'a day keeps the doctor away')

b = 10
print( b , 'apples a day keeps the doctor away')

b = 10
print( b + 'apples a day keeps the doctor away')