# -*- coding: utf-8 -*-
"""ch1-lab-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N5mTWE9MPxwuWQy5Uw70Fsz8F6qzAFuZ
"""

eng = int(input())
math = int(input())
if ( eng and math ) >= 60 :
  print('因為英文得{}分和數學得{}分所以去吃海底撈'.format(eng, math))

elif ( eng or math ) >= 60 :
  print('因為英文得{}分和數學得{}分所以吃肯德基'.format(eng, math))

else:
  print('因為英文得{}分和數學得{}分所以去罰站'.format(eng, math))