# -*- coding: utf-8 -*-
"""ch3_class-2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CdaPTb4lLVm_mWmXk6glmrWM0efAPyYl
"""

import pandas as pd         
import numpy as np         
import matplotlib.pyplot as plt

# 使用pandas讀檔
company = pd.read_csv('/content/company_revenue-ver2.csv')

# 檢視前幾列和標頭
company.head()

print(type(company['出表日期']))

import pandas as pd
company = pd.DataFrame({
    '出表日期':[1100717, 1100717, 1100717, 1100717, 1100717],
    '資料年月':[11006, 11006, 11006, 11006, 11006],
    '公司代號':[1101, 1102, 1103, 1104, 1108],
    '公司名稱':['台泥', '亞泥', '嘉泥', '環泥', '幸福'],
    '產業別':['水泥工業', '水泥工業', '水泥工業', '水泥工業', '水泥工業'],
    '營業收入-當月營收':['$8,480,821.00', '$6,895,504.00', '$168,756.00', '$407,130.00', '$325,660.00']
 })
company.head()

# 看看資料有多少列，是否有遺漏值，以及每一行的資料類型
company.info() #可以看到資料有954筆(列)，且有14個屬性(欄)

# 計算遺漏值數量的方法
company.isnull().sum()

# 顯示描述性統計
company.describe()

'''使用Pandas的map功能，將函數映射到整個資料集：'''
# 為了視覺化需要刪除錢符號
company ['營業收入-當月營收'] = company ['營業收入-當月營收'].map(lambda value: value.replace('$',''))

# 檢查是否已刪除乾淨
company.head()

#嘗試轉換資料型態
company ['累計營業收入-去年累計營收'] = company['累計營業收入-去年累計營收'].astype('float')
company.info()