# -*- coding: utf-8 -*-
"""ch3_class-2-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EUxY_4i-7zCjV9RMJyXcLkhDUDJICJoS
"""

import pandas as pd         
import numpy as np         
import matplotlib.pyplot as plt

# 使用pandas讀檔
company = pd.read_csv('/content/company_revenue-ver2.csv')

#對產業類別計數
company_industry = company['產業別'].value_counts()
company_industry.head

#對產業別遞減排序
company_industry = company_industry.sort_values(ascending=False)
company_industry_in = company_industry.index
print(company_industry)
print(company_industry_in)

#對產業別繪製長條圖
#方法一、使用matplotlib
plt.figure(figsize = (8,8))
plt.bar(company_industry_in,company_industry,)
plt.show()


#方法二、使用pandas內的matplotlib函式
# company_industry.head(20).plot(kind='bar')

#對產業別繪製圓餅圖
#方法一、使用matplotlib
plt.figure(figsize = (10,15))
# company_industry = company_industry.astype('float')
plt.pie(company_industry,labels =company_industry_in)
plt.show()

#對產業別繪製圓餅圖
#方法二、使用pandas內的matplotlib函式
# company_industry.plot(kind='pie')