# -*- coding: utf-8 -*-
"""ch3_lab2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smYe0_tYimK31HaWSg-u81bTFreZDRAS
"""

import pandas as pd         
import numpy as np         
import matplotlib.pyplot as plt

# 使用pandas讀檔
company = pd.read_csv('/content/company_revenue-ver2.csv')

# 檢視前幾列和標頭
company.head()

# 看看資料有多少列，是否有遺漏值，以及每一行的資料類型
company.info() #可以看到資料有954筆(列)，且有14個屬性(欄)
# 顯示描述性統計
company.describe()

'''使用Pandas的map功能，將函數映射到整個資料集：'''
# 為了使用describe函數在company ['營業收入-當月營收']，需要刪除錢符號、逗點、空格、-號
company ['營業收入-當月營收'] = company ['營業收入-當月營收'].map(lambda value: value.replace('$',''))
company ['營業收入-當月營收'] = company ['營業收入-當月營收'].map(lambda value: value.replace(',',''))
company ['營業收入-當月營收'] = company ['營業收入-當月營收'].map(lambda value: value.replace(' ',''))
company ['營業收入-當月營收'] = company ['營業收入-當月營收'].map(lambda value: value.replace('-','0'))

# 檢查是否已刪除乾淨
company.head()

company.info() #營業收入-當月營收的Dtype仍舊是object，我們需要將它轉換成numeric的型態才可以使用描述性統計函式describe()

company ['營業收入-當月營收'] = company['營業收入-當月營收'].astype('float')
company.info()
company.describe()