# -*- coding: utf-8 -*-
"""ch3_class-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u_vvJSgM823ZYQ-aGcyZhPos0NvsmagY
"""

import pandas as pd
spending_df = pd.DataFrame({
    '生活費':[8000, 7000],
    '娛樂費':[3000, 5000],
    '交通費':[1000, 1200]

 })
spending_df.head()

#新增一欄
spending_df['住宿費'] = [8000, 8000]
spending_df

#新增一列，如該列有資料則直接取代該列
spending_df.loc[2]=[7500, 4000, 1200, 8000]
spending_df

#改變df欄名稱(axis = 1)
rename_attribute = {'生活費':'110年生活費','娛樂費':'110年娛樂費','交通費':'110年交通費','住宿費':'110年住宿費'}
spending_df = spending_df.rename(rename_attribute, axis=1)
spending_df

#改變df列index(axis = 0)
rename_index = {0:'一月',1:'二月',2:'三月'}
spending_df = spending_df.rename(rename_index, axis=0)
spending_df

#儲存成csv檔
spending_df.to_csv('spending_df.csv')

#讀檔
spending_df = pd.read_csv('spending_df.csv')
spending_df

#讀檔，使第一欄成為index
spending_df = pd.read_csv('spending_df.csv',index_col=0)
spending_df

spending_df_tmp = spending_df

#刪除df欄資料(axis = 1)
columns_drop = ['110年交通費', '110年住宿費']
spending_df = spending_df.drop(columns_drop, axis=1)
spending_df

#刪除列資料(axis = 0)
rows_drop = ['二月', '三月']
spending_df = spending_df.drop(rows_drop, axis=0)
spending_df

spending_df = spending_df_tmp
spending_df

#重置列索引
#方法一
spending_df = spending_df.reset_index()#inplace=False
spending_df

spending_df = spending_df_tmp
spending_df

#重置列索引
#方法二
spending_df = spending_df.reset_index(drop=True)
spending_df

spending_df = spending_df_tmp
spending_df

#查詢欄資料
spending_df['110年交通費']

#查詢列資料
spending_df.loc['一月']

#查詢單一值
spending_df['110年交通費']['一月']

#無視欄名稱和列index，查詢欄資料
spending_df.iloc[:,2]

#無視欄名稱和列index，查詢列資料
spending_df.iloc[0,:]

#無視欄名稱和列index，查詢單一值
spending_df.iloc[0,2]

#宣告一個新的df
earning_df = pd.DataFrame({
        '110年薪資收入':[21000, 21000, 22000],
        '110年股票收入':[1000, 0 ,200]
        })
earning_df

#宣告一個新的df
spending45_df = pd.DataFrame({
        '110年生活費':[9000, 8000],
        '110年娛樂費':[5000, 1200],
        '110年交通費':[1000, 0],
        '110年住宿費':[8000, 8000]
        })
spending45_df

#合併兩個df，合併方向為axis=1
property_df = pd.concat([spending_df,earning_df],axis=1)
property_df

#合併兩個df，合併方向為axis=0
property_df = pd.concat([spending_df,spending45_df],axis=0)
property_df

#合併兩個df，合併方向為axis=0，忽略兩個df的index
property_df = pd.concat([spending_df,spending45_df],axis=0, ignore_index=True)
property_df

#使用遮罩(mask)查詢
mask1 = spending_df['110年生活費'] == 7000
spending_df[mask1]

#使用遮罩(mask)查詢
mask2 = spending_df['110年交通費'] > 1000
spending_df[mask2]

#使用遮罩(mask)查詢，包含兩個條件，需兩個條件都成立
#方法一
spending_df[(mask1 & mask2)]

#使用遮罩(mask)查詢，包含兩個條件，需兩個條件都成立
#方法二
spending_df[(spending_df['110年生活費'] == 7000) & (spending_df['110年交通費'] > 1000)]

#使用遮罩(mask)查詢，包含兩個條件，有其中一個條件真則判斷為真
spending_df[(mask1 | mask2)]