# -*- coding: utf-8 -*-
"""ch4_class-1-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L4tVtyc4vWA0VTdcI8PriK2GzpxQxYcT
"""

import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt  
pima_df = pd.read_csv('pima.csv')

for i in ['serum_insulin', 'bmi', 'plasma_glucose_concentration', 'diastolic_blood_pressure', 'triceps_thickness']:
  pima_df[i] = pima_df[i].replace([0],[None])

pima_dropped = pima_df.dropna()

pima_df['onset_diabetes'].value_counts(normalize=True)

pima_dropped['onset_diabetes'].value_counts(normalize=True)

pima_df

pima_df.mean()

pima_dropped.mean()

#平均值變化百分比
change = (pima_dropped.mean() - pima_df.mean()) / pima_df.mean() #矩陣運算
change