# -*- coding: utf-8 -*-
"""ch4_lab-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HoX7VvCOupP2tDTKOi4krb5O_tOcoBqg
"""

import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt  
pima_df = pd.read_csv('pima.csv')

for i in ['serum_insulin', 'bmi', 'plasma_glucose_concentration', 'diastolic_blood_pressure', 'triceps_thickness']:
  pima_df[i] = pima_df[i].replace([0],[None])

pima_dropped = pima_df.dropna()

print(type(pima_df.shape[0]))# - pima_dropped.shape[0])

#lab1-1
num_rows_lost = pima_df.shape[0] - pima_dropped.shape[0]
percent_rows_lost = round(100*(num_rows_lost/pima_df.shape[0]))
print('刪除了{}筆資料，共佔原資料集資料數的{}%'.format(num_rows_lost, percent_rows_lost))

change = (pima_dropped.mean() - pima_df.mean()) / pima_df.mean() #矩陣運算
change

#lab1-2
plt.figure(figsize = (10,15))
plt.bar(change.index, change)
plt.show()