# -*- coding: utf-8 -*-
"""ch4_class-1-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ww-JdA0RKrRpHw5FO7EZ554QDOvbhduT
"""

import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt  
pima_df = pd.read_csv('pima.csv')

'''
pima_column_names = ['times_pregnant', 'plasma_glucose_concentration', 'diastolic_blood_pressure', 'triceps_thickness', 'serum_insulin', 'bmi', 'pedigree_function', 'age', 'onset_diabetes']
pima_column_names = ['懷孕次數', '口服葡萄糖耐量試驗中的2小時血漿葡萄糖濃度', '舒張壓', '三頭肌皮脂厚度', '2小時血清胰島素濃度', 'bmi', '糖尿病家族函數', 'age', '類別變數(0或1，代表有無或有糖尿病']
'''

pima_df.isnull().sum()

pima_df.describe()

for i in ['serum_insulin', 'bmi', 'plasma_glucose_concentration', 'diastolic_blood_pressure', 'triceps_thickness']:
  pima_df[i] = pima_df[i].replace([0],[None])

pima_df.isnull().sum()

pima_df.describe()

null = pima_df['plasma_glucose_concentration'].isnull()
null

pima_df[null] ##查出plasma_glucose_concentration有缺失的資料

pima_dropped = pima_df.dropna()

pima_dropped.isnull().sum()